steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['mvn' ,'clean' ,'deploy' ,'-Ddocker.user=$$DOCKERUSERNAME' ,'-Ddocker.password=$$DOCKERPASSWORD' ,'-Ddocker.url=mdnurakmal/springboot-demo-1']
    secretEnv: [ '$$DOCKERUSERNAME', '$$DOCKERPASSWORD' ]

