steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ 'clean' ,'install']

  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['clean' ,'deploy' ,'-Ddocker.user=$$DOCKERUSERNAME' ,'-Ddocker.password=$$DOCKERPASSWORD' ,'-Ddocker.url=https://hub.docker.com/repository/docker/mdnurakmal/springboot-demo-1']
    secretEnv: [ 'DOCKERUSERNAME', 'DOCKERPASSWORD' ]

availableSecrets:
  secretManager:
    - versionName: projects/test-327905/secrets/DOCKERUSERNAME/versions/1
      env: 'DOCKERUSERNAME'
    - versionName: projects/test-327905/secrets/DOCKERPASSWORD/versions/1
      env: 'DOCKERPASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY