steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ 'spring-boot:build-image']

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login -u=$$DOCKERUSERNAME -p=$$DOCKERPASSWORD
        docker build -t mdnurakmal/springboot-demo-1:latest .
        docker push mdnurakmal/springboot-demo-1:latest
    secretEnv: [ 'DOCKERUSERNAME', 'DOCKERPASSWORD','FIRESTORE_SA' ]


#      # deploy container image to GKE
#  - name: "gcr.io/cloud-builders/gke-deploy"
#    args:
#      - '-c'
#      - |
#        export GOOGLE_APPLICATION_CREDENTIALS=$$FIRESTORE_SA
#      - gke-deploy run --filename=deployment.yaml --location=my-kubernetes-cluster --cluster=us-central1-c
#    secretEnv: [ 'FIRESTORE_SA' ]

availableSecrets:
  secretManager:
    - versionName: projects/test-327905/secrets/DOCKERUSERNAME/versions/1
      env: 'DOCKERUSERNAME'
    - versionName: projects/test-327905/secrets/DOCKERPASSWORD/versions/1
      env: 'DOCKERPASSWORD'
    - versionName: projects/test-327905/secrets/FIRESTORE_SA/versions/1
      env: 'FIRESTORE_SA'


options:
  logging: CLOUD_LOGGING_ONLY