apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  application.properties: |-
    spring.kafka.producer.bootstrap-servers =  10.3.245.18
    spring.kafka.consumer.bootstrap-servers =  10.3.245.18