apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json:
    '{
      "spring.kafka.producer.bootstrap-servers": "kafka",
      "spring.kafka.consumer.bootstrap-servers": "kafka",
     }'