apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  application.yml: |-
    spring:
      kafka:
        producer:
          bootstrap-servers: 10.3.245.18
        consumer:
          bootstrap-servers: 10.3.245.18