apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: mdnurakmal/springboot-demo-1:latest
          name: springboot-demo-1
          env:
          - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: spring-config
                key: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
          - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: spring-config
                key: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
          resources: {}

status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}
